name: Gemini Scheduled PR Triage ðŸš€

on:
  workflow_dispatch: {}

jobs:
  audit-prs:
    timeout-minutes: 15
    if: ${{ github.repository == 'google-gemini/gemini-cli' }}
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      prs_needing_comment: ${{ steps.run_triage.outputs.prs_needing_comment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Run PR Triage Script
        id: run_triage
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./.github/scripts/pr-triage.sh
